import type { Metadata } from "next";
import { ThemeProvider } from 'next-themes'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="ja" suppressHydrationWarning>
        <body>
          <ThemeProvider defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </body>
      </html>
  );
}
